version: '3.9'

services:
  postgres:
    image: postgres:15.3-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    healthcheck:
      test: "exit 0"

  app:
    build:
      context: ./app
    ports:
      - "8080:8080"
      - "99:99"
    restart: always
    depends_on:
        postgres:
          condition: service_healthy
    volumes:
      -  ./app:/app



