#FROM python:3.10.1-buster
#WORKDIR /app
#
#COPY ./requirements.txt /app/requirements.txt
#RUN pip install -r requirements.txt
#EXPOSE 8080
#COPY . /app
#
#CMD ["python", "app"]

FROM python:3.10.1-buster

RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -

RUN sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'

RUN apt-get -y update

RUN apt-get install -y google-chrome-stable

RUN apt-get install -yqq unzip

RUN wget -O /tmp/chromedriver.zip http://chromedriver.storage.googleapis.com/`curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE`/chromedriver_linux64.zip

RUN unzip /tmp/chromedriver.zip chromedriver -d /usr/local/bin/

ENV DISPLAY=:99
EXPOSE 99
WORKDIR /app

COPY ./requirements.txt /app/requirements.txt
RUN pip install -r requirements.txt
EXPOSE 8080
COPY . /app

CMD ["python", "-u", "app"]


